.Documentation/docfx.json
.azure-documentation-release.yml

- add: Added new azure pipeline for building and publishing the creator documentation.

Setup CI for documentation release with Azure Pipelines

---

Tests/Locking.meta
Tests/Locking/LockingTests.cs
Tests/Locking/LockingTests.cs.meta
Tests/Utils/Mocks/Conditions/LockableReferencingConditionMock.cs
Tests/Utils/Mocks/Conditions/LockableReferencingConditionMock.cs.meta
Tests/Utils/Mocks/Conditions/ReferencingConditionMock.cs
Tests/Utils/Mocks/Conditions/ReferencingConditionMock.cs.meta
Tests/Utils/Mocks/Properties/ILockablePropertyMock.cs
Tests/Utils/Mocks/Properties/ILockablePropertyMock.cs.meta
Tests/Utils/Mocks/Properties/LockablePropertyMock.cs
Tests/Utils/Mocks/Properties/LockablePropertyMock.cs.meta
Tests/Utils/Mocks/Properties/LockablePropertyMockWithDependency.cs
Tests/Utils/Mocks/Properties/LockablePropertyMockWithDependency.cs.meta
Tests/Utils/Mocks/Properties/PropertyMock.cs
Tests/Utils/Mocks/Properties/PropertyMockWithDependency.cs

Adds unit tests for the new autolocking feature.
**Fixes**: [TRNG-930](https://jira.innoactive.de/browse/TRNG-930)
Unit tests ran through on my system.

Add unit tests for autolocking feature

---

Runtime/LockableObjectsCollection.cs

Cleanup and documentation in LockableObjectsCollection.

chore: add documentation and cleanup lockable objs collection

---

Tests/Locking/LockingTests.cs

Tests for lockable objects collection.
Run the tests?!

feat: add tests for lockable objects collection

---

Runtime/Configuration/BaseRuntimeConfiguration.cs
Runtime/CourseRunner.cs
Runtime/RestrictiveEnvironment/DefaultStepLockHandling.cs
Runtime/RestrictiveEnvironment/StepLockHandlingStrategy.cs
Runtime/SceneObjects/SceneObjectReference.cs

Locking mechanic will now be configured via current set mode, by given method.

feat(locking): made StepLockingStrategy configureable by modes

---

.Documentation/articles/developer/10-lockable-properties.md
.Documentation/articles/innoactive-creator/suspending-interactions.md

Minor fixes to the docu which I forgot to save in the editor.

docs(locking): minor fixes to the docu

---

.Documentation/articles/developer/10-lockable-properties.md

Extended locking documentation which additional information about how to integrated locking in your project.

docs: extended locking documentation

---

.Documentation/articles/developer/10-lockable-properties.md

Remove parameter from docu which is not used anymore.

fix: remove wrong parameter from docu

---

.Documentation/articles/developer/11-text-to-speech.md
.Documentation/articles/images/developer/play-text-to-speech-example.png

Adapted documentation about TTS to reflect the changes 2.0 text to speech stuff

docu: reworked documentation about text to speech trng-885

---

Editor/PackageExporter.cs

Added a little bit more debug logging when exporting stuff, should help us to detect error in ci faster.

ci: improved logging of exporter to ease ci integration

---

Editor/UI/Graphics/Renderers/GridRenderer.cs
Editor/UI/Windows/CourseWindow.cs

Fixed by including the scrolling into the grid drawing limit.
Visual in edtior :P

fix: fixed training window grid stopping rendering

---

.Documentation/articles/setup-guides/03-project-setup.md
.Documentation/articles/transition-to-v2.0/01-overview-of-the-changes.md

**Fixes**: # References to .net compatibility level were removed from the documentation

References to .net configuration were removed from the documentation TRNG-1051

---

Editor/UI/Wizard/FirstTime/TrainingSceneSetupPage.cs
Editor/UI/Wizard/Logic.meta
Editor/UI/Wizard/Logic/SceneSetupLogic.cs
Editor/UI/Wizard/Logic/SceneSetupLogic.cs.meta
Editor/UI/Wizard/WizardPage.cs
Editor/UI/Wizard/WizardWindow.cs

 feat: wizard scene setup page

---

.Documentation/articles/developer/09-conditions.md

Some scripts (`UpsideDownConditionAutocompleter` and `UpsideDownConditionActiveProcess`) were outdated since v2.0.0. They are updated now.
**Fixes**: [TRNG-1011](https://jira.innoactive.de/browse/TRNG-1011)
Tested the scripts in the whole article and corrected them. Read through the whole article.

docs: fix scripts in conditions article

---

Editor/UI/Drawers/FloatDrawer.cs
Editor/UI/Drawers/TabsGroupDrawer.cs

ci: release v2.4.1

---

.Documentation/articles/developer/TBD-01-runtime-configuration.md
.Documentation/articles/developer/TBD-02-editor-configuration.md
.Documentation/articles/developer/TBD-03-training-modes.md
.Documentation/articles/developer/TBD-04-configurators.md
.Documentation/articles/developer/TBD-05-mode-parameters.md
.Documentation/articles/developer/TBD-06-localization.md
.Documentation/docfx.json

Replace "TBD" in dev's docu in chapters under construction with meaningful messages
I had read it out loud and clicked the links.

docs: replace TBD with a meaningful message

---

.Documentation/articles/images/step-by-step-guides/behavior.jpg
.Documentation/articles/images/step-by-step-guides/createSnapZone.jpg
.Documentation/articles/images/step-by-step-guides/creatorWindows.jpg
.Documentation/articles/images/step-by-step-guides/unityWindows.jpg
.Documentation/articles/setup-guides/03-xr-setup.md
.Documentation/articles/setup-guides/index.md
.Documentation/articles/step-by-step-guides/hello-creator.md
.Documentation/articles/step-by-step-guides/index.md
.Documentation/articles/toc.yml
Editor/Setup/SceneSetupUtils.cs
Editor/UI/Wizard/Setup/TrainingSceneSetupPage.cs
Editor/UI/Wizard/WizardWindow.cs

docs: new hello creator guide
This PR enables a new step by step guide.
Select create a new training course and follow the wizard until the second-page `Setup Training`, then instead of creating a new training course select `Load Step by Step Guide Scene`.
Also, take a look at the documentation.

feat(wizard): new step by step guide TRNG-1124

---

Runtime/SceneObjects/ObjectReference.cs
Runtime/Utils/Audio/IAudioData.cs
Runtime/Utils/Audio/ResourceAudio.cs
Runtime/Utils/ICanBeEmpty.cs
Runtime/Utils/ICanBeEmpty.cs.meta
Runtime/Utils/ReflectionUtils.cs

Added new interface to enable classes to be checked for beeing empty.

Added new interface for checking empty stuff

---

Runtime/SceneObjects/ObjectReference.cs
Runtime/Utils/Audio/IAudioData.cs
Runtime/Utils/Audio/ResourceAudio.cs
Runtime/Utils/ICanBeEmpty.cs
Runtime/Utils/ICanBeEmpty.cs.meta
Runtime/Utils/ReflectionUtils.cs

chore: added new interface for checking if something is empty

---

Editor/UI/CreatorMenu/CommunityMenuEntry.cs
Editor/UI/CreatorMenu/CommunityMenuEntry.cs.meta
Editor/UI/CreatorMenu/DocumentationMenuEntry.cs
Editor/UI/CreatorMenu/DocumentationMenuEntry.cs.meta
Editor/UI/CreatorMenu/SupportMenuEntry.cs
Editor/UI/CreatorMenu/WebinarMenuEntry.cs
Editor/UI/CreatorMenu/WebinarMenuEntry.cs.meta

Help menu now also contains:
* Link to Community
* Link to Webinar
* Link to Documentation

feat: Improved help options in menu

---

Editor/Analytics/AnalyticsSetup.cs
Editor/Analytics/AnalyticsUtils.cs
Editor/Analytics/BaseAnalyticsTracker.cs
Editor/Analytics/GoogleTracker.cs
Editor/Analytics/IAnalyticsTracker.cs

Improved tracking, sending a proper start session, added user agent (unity), and added pro id.

refactor: improved tracking information

---

Editor/UI/Wizard/Setup/CreatorSetupWizard.cs
Editor/UI/Wizard/WizardWindow.cs

Added a new public event which is invoked when the CreatorSetupWizard is closed.

feat: setup wizard now has an closed event

---

Editor/UI/Windows/CourseWindow.cs

Added middle mouse panning for the workflow editor.
ticket: TRNG-1286

feat: added middle mouse panning #TRNG-1286

---

Editor/UI/Wizard/Setup/XRSDKSetupPage.cs
Editor/UI/Wizard/WizardWindow.cs

**Fixes**: An issue that prevented the XR configuration to be executed.
Given a project that contains the XR Interaction component and it has no XR configuration yet, launch the wizard, and select any hardware configuration.

fix: issue that prevented the xr setup to work

---

.Documentation/articles/innoactive-creator/default-conditions.md

Updating docu accourding to https://github.com/Innoactive/Basic-Conditions-And-Behaviors/pull/34
**Fixes**: TRNG-1251

docs: update object in range condition docu

---

Editor/UI/Windows/CourseWindow.cs

fix for https://jira.innoactive.de/browse/TRNG-1246

fix: course will be revalidated when course view is focused

---

Editor/UI/EditorDrawingHelper.cs

Increase stroke size of step transitions so it is more visible to users.
- [ x] Bug fix (non-breaking change which fixes an issue)
- create two steps and connect them.
- [ x] My code follows the [Coding Conventions](#coding-conventions)
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings

fix: increase stroke size of step transitions

---

Editor/UI/Graphics/TransitionElement.cs

Removed the curve thingi from straight lines which improves the visual quality a lot.

feat: removed beziercurves from straight lines

---

Editor/Analytics/AnalyticsSetup.cs
Editor/Analytics/VersionCheckerEvent.cs
Editor/Analytics/VersionCheckerEvent.cs.meta
Editor/CreatorProjectSettings.cs

Integrates following additional tracking data:
(daily) using creator with license free, trial, customer
(on updating creator) updated creator to version X
According ticket: https://jira.innoactive.de/browse/TRNG-1222

feat: improved tracking of user updating and pro status #trng-1222

---

Editor/Resources/icon_add_dark.png.meta
Editor/Resources/icon_add_light.png.meta
Editor/Resources/icon_arrow_right_dark.png.meta
Editor/Resources/icon_arrow_right_light.png.meta

Missing meta files causing problems with icons.

chore: added missing meta files

---

Editor/UI/ProjectSettings/LoggingSettingsSection.cs
Runtime/Utils/SettingsObject.cs

We saved too often which led to lagging inputs.

fix: creator settings are not lagging anymore

---

Runtime/Utils/LockObjectsOnSceneStart.cs
Runtime/Utils/LockObjectsOnSceneStart.cs.meta

Removed this script from the template and added it to core.

feat: add lock objects on scene start

---

Editor/UI/Drawers/UniqueNameReferenceDrawer.cs

Error message while only be shown once (per recompile) per broken unique name reference

fix: fixed spam for broken unique name references

---

Editor/UI/Graphics/Renderers/ExitJointRenderer.cs

added outgoing icons to all exit transitions
- [x ] Bug fix (non-breaking change which fixes an issue)

fix: add outgoing icon to all exits

---

Editor/UI/Graphics/EntryNode.cs
Editor/UI/Graphics/Renderers/EntryNodeRenderer.cs
Editor/UI/Windows/ChapterRepresentation.cs

added hover and pressed color to entry node.
- [ x] Bug fix (non-breaking change which fixes an issue)

fix: add pressedColor and hover to EntryNode

---

Editor/UI/Drawers/ConditionInstantiatorDrawer.cs
Editor/UI/Drawers/MetadataWrapperDrawer.cs
Editor/UI/Drawers/NameableDrawer.cs
Editor/UI/Drawers/TransitionInstantiatiorDrawer.cs

Improved Step Inspector design

---

.github/CONTRIBUTING.md

Replaced Aleksei with Thomas as active maintainer.

chore: updated maintainer

---

Editor/Setup/SceneSetup.cs

Extracted the finding part of the SetupPrefab method from setting it actually up.

chore: extended scene setup functionality

---

.Documentation/articles/images/default-behaviors/interactable-highlighter-script.png
.Documentation/articles/innoactive-creator/default-behaviors.md
Editor/Resources/icon_help_dark.png.meta
Editor/Resources/icon_help_light.png.meta
Editor/UI/Drawers/MetadataWrapperDrawer.cs
Runtime/Attributes/HelpAttribute.cs.meta
Runtime/Attributes/HelpLinkAttribute.cs.meta

Updated the behaviors documentation
links to 
https://github.com/Innoactive/Basic-Conditions-And-Behaviors/pull/38

fix: updated the behaviors help

---

Runtime/CourseEventArgs.cs
Runtime/CourseEventArgs.cs.meta
Runtime/CourseRunner.cs

Minor changes which allows people to easily get course events on runtime. This will already be used for the DesktopMode setup and also makes the StepTracker obsolete which is very nice.

feat: added course events to the CourseRunner required for TRNG-1414

---

.Documentation/articles/images/localization/key-mapping.png
.Documentation/articles/images/localization/language-files.png
.Documentation/articles/images/localization/menu-languages.png
.Documentation/articles/innoactive-creator/index.md
.Documentation/articles/innoactive-creator/localization.md
.Documentation/articles/toc.yml
Runtime/ILockableStepData.cs.meta
Runtime/Localization/Localization.cs
Runtime/Localization/LocalizationConfig.cs
Runtime/Localization/LocalizationConfig.cs.meta
Runtime/Localization/LocalizationReader.cs
Runtime/Localization/LocalizationReader.cs.meta
Runtime/Localization/LocalizationUtils.cs
Runtime/Resources.meta
Runtime/Resources/Localization.meta
Runtime/Resources/Localization/Creator.txt
Runtime/Resources/Localization/Creator.txt.meta
Runtime/Resources/Localization/Creator_DE.txt
Runtime/Resources/Localization/Creator_DE.txt.meta
Runtime/Resources/Localization/Creator_EN.txt
Runtime/Resources/Localization/Creator_EN.txt.meta
Runtime/Resources/Localization/DefaultLocalization.asset
Runtime/Resources/Localization/DefaultLocalization.asset.meta
Runtime/Resources/Localization/StandaloneLocalization.asset
Runtime/Resources/Localization/StandaloneLocalization.asset.meta

Improved localization by adding new logic which uses localization configs to properly load the language.
Missing: Updated documentation.
Needs: https://github.com/Innoactive/Basic-UI-Component/pull/18
Localization should still work the same then before, for the training designer there should be no changes at all.

Improved localization for TRNG-1414

---

.Documentation/articles/images/default-conditions/snapzonegenerator.png
.Documentation/articles/images/default-conditions/snapzoneparameters.png
.Documentation/articles/images/default-conditions/snapzonesettings.png
.Documentation/articles/innoactive-creator/default-conditions.md
.Documentation/articles/innoactive-creator/general-concepts.md
.Documentation/articles/innoactive-creator/transitions.md
.Documentation/articles/toc.yml

doc: continue in github

---

.Documentation/articles/images/default-conditions/defaultteleportationanchor.gif
.Documentation/articles/images/default-conditions/teleportationproperty.PNG
.Documentation/articles/innoactive-creator/default-conditions.md

Documentation for Teleport Condition

Documentation for Teleport Condition TRNG-102

---

Runtime/IO/DefaultFileSystem.cs

Bug when using the FileManager for reading files on windows.

fix: issue when reading persistent files on windows

---

.Documentation/articles/innoactive-creator/localization.md

fix: typo in path fixed and clarification

---

Editor/Setup/SceneSetup.cs

The instantiated object on scene setup is now returned so it can be changed afterwards if needed.
Related PRs:
https://github.com/Innoactive/Basic-UI-Component/pull/25

refactor: set up object is now returned

---

Runtime/CourseRunner.cs
Runtime/FastForwardCourseEventArgs.cs
Runtime/FastForwardCourseEventArgs.cs.meta

* statics events are no good for scene related stuff, breaks stuff far to easy, changed that
* added new fast forward event

chore: moved course events to non static, added fastforward event

---

README.md

I added to the creator readme file the fact that users also need to clone the basic UI components to be able to run for example the desktop mode.

fix: add basic ui components
