.azure-pipelines.yml
When we rerun the failed stage build we probably get multiple log artifacts, which all should be saved, so I extended the artifact name with the build id which hopefully changes on stage reruns (not checked right not).
Well, someone (me), dropt the pathes for the project for nearly all u3d calls, which led to this strange behavior. Readded them to fix the problem.
=> ci: adapted log-artifact name to show the build id

.github/CONTRIBUTING.md
coding conventions section in contributing was linking to itself while it should point to our coding conventions.
* Link to coding convention works now.
=> docu: fixed the link to the coding conventions

.dependencies.json, Runtime/Properties/LockableProperty.cs, Runtime/RestrictiveEnvironment/PropertyReflectionHelper.cs
Every step unlocks at its start all the scene objects that have at least one `Lockable Property` and their dependencies and then lock them back at the end of its execution.
Create a new training course and play around with multiple steps and different variants between `Touch Condition`, `Grab Condition`, `Use Condition`, `Snap Condition`.
=> Steps lock/unlock training properties and their dependencies TRNG-55

Editor/Configuration/AllowedMenuItemsSettings.cs, Editor/UI/StepInspector/Menu/IInternalTypeProvider.cs, Editor/UI/StepInspector/Menu/IInternalTypeProvider.cs.meta, Editor/UI/StepInspector/Menu/MenuItem.cs
Obsoleted Behaviors & Conditions wont show up in default "Add Behavior/Condition" menu.
=> chore: allowed menu items hide obsoleted behaviors & conditions by default

Runtime/LockableObjectsCollection.cs
When exiting playmode the scene will be reloaded which breaks scene references which already caching GameObjects. Fixed be flushing those scene references on playmode exit.
=> fix: cleared caching for scene object references on playmode exit

Runtime/LockableObjectsCollection.cs, Runtime/Properties/PropertyReflectionHelper.cs, Runtime/RestrictiveEnvironment/DefaultStepLockHandling.cs
* Added a not so nice way to get the next step, if the current step is at the end of a chapter. Which is done by crawling the whole course data tree.
* Renamed ExtractLockablesFromStep to ExtractLockableFromStep
=> feat: locking will now also find the next chapters first step

.Documentation/articles/toc.yml
Fixed typo in table of contents: from propertiees to properties.
=> docu: fixed typo in table of content

Editor/UI/Drawers/Metadata.meta, Editor/UI/Drawers/Metadata/ReorderableElementMetadata.cs, Editor/UI/Drawers/Metadata/ReorderableElementMetadata.cs.meta, Editor/UI/Drawers/MetadataWrapperDrawer.cs, Editor/UI/Drawers/ObjectDrawer.cs, Runtime/Attributes/ReorderableListOfAttribute.cs, Runtime/Attributes/ReorderableListOfAttribute.cs.meta, Runtime/BehaviorCollection.cs, Runtime/Transition.cs, Runtime/TransitionCollection.cs
In the Step Inspector all behaviors, transitions, and conditions are reorderable now. They can be moved up and down. Therefore, a new 'ReorderableListOfAttribute' attribute is introduced.
**Fixes**: [TRNG-495](https://jira.innoactive.de/browse/TRNG-495)
This was tested manually, since it's a UI change.
**Test Configuration**: Home PC, Unity 2019.4.1f1 LTS
=> feat: behaviors, transitions, and conditions are reorderable

Editor/UI/Drawers/ObjectDrawer.cs, Runtime/Attributes/ListOfAttribute.cs, Runtime/Metadata.cs
This fixes the bug when you can't drag transitions if you have the transition view open for a step that was created before v2.1.
**Fixes**: #948
I clicked around to see if it fixes the issue or breaks something else. More of clicking around is required.
=> fix: update obsolete metadata properly

.Documentation/articles/images/step-inspector/add-behavior.gif, .Documentation/articles/images/step-inspector/add-condition.gif, .Documentation/articles/images/step-inspector/add-transition.gif, .Documentation/articles/images/step-inspector/change-description.gif, .Documentation/articles/images/step-inspector/icon_arrow_down_dark.png, .Documentation/articles/images/step-inspector/icon_arrow_up_dark.png, .Documentation/articles/images/step-inspector/icon_delete_dark.png, .Documentation/articles/images/step-inspector/open-inspector.gif, .Documentation/articles/images/step-inspector/rename-step.gif, .Documentation/articles/images/step-inspector/reorder-entities.gif, .Documentation/articles/images/step-inspector/unlock-objects.gif, .Documentation/articles/innoactive-creator/step-inspector.md
The Step Inspector article of our documentation is now updated.
New images (gifs and pngs) and descriptions for reordering and unlocking objects are added.
**Fixes**: # [TRNG-495](https://jira.innoactive.de/browse/TRNG-495)
I read it.
=> docs: step inspector article is updated

Editor/DefaultEditingStrategy.cs
**Fixes**: # The `DefaultEditingStrategy` reset the step window view when entering play mode or edit mode, unfortunately, it assumes that the step window is always opened, throwing an NRE when it is not. 
Open a training scene, make sure the step editor is closed, play the scene, and then stop it, no need to run the course.
=> DefaultEditingStrategy now checks if StepWindow exits before calling it.

.azure-pipelines.yml
Moved release down so we don't create a new version before we check everything is working.
Added missing version export
=> ci: moved the release creation and exporting version now

Editor/UI/Graphics/StepNode.cs
Position between EntryNode and StepNode on the same y-Level is off by one pixel. Fixed by moving the EntryJoint of the StepNode up by one pixel because it was off.
Fixes: https://jira.innoactive.de/browse/TRNG-946
Previous:
Now:
=> fix: position of line between entry node and step node

Runtime/RestrictiveEnvironment/DefaultStepLockHandling.cs
Now checking for null when getting the first steps data.
=> fix(locking): fixed npe when chapter has no steps

Editor/UI/Wizard/Setup/AllAboutPage.cs, README.md
Prevents link to community from breaking when community's url changes or community is moved off spectrum.chat.
Ran through wizard, clicked on the Community Link, browser opened at `https://innoactive.io/creator/community` and redirected automatically to `https://spectrum.chat/innoactive-creator`
=> fix: dynamic link to community

Editor/Unity/AssemblySymbolChecker.cs, Editor/Unity/AssemblySymbolChecker.cs.meta
The added script checks for specific assemblies exist and adds/removes a symbol accordingly.
**Fixes**: 
- Problems with integrating pro stuff for specific components.
BASIC_INTERACTION symbol is only existent when the assemblie for it is loaded.
=> feat(assembly-checker): added assembly checker for symbols

Editor/Analytics/AnalyticsSetup.cs, Editor/Analytics/AnalyticsState.cs, Editor/Analytics/AnalyticsUtils.cs, Editor/Analytics/GoogleTracker.cs, Editor/UI/ProjectSettings/AnalyticsSettingsProvider.cs, Editor/UI/Wizard/Setup/AnalyticsPage.cs
Analytics code got refactored.
* There is now only the "enabled" and the "disabled" option left.
* Disabling analytics now sends one last message to analytics.
* The generated user ID does not start with IA anymore.
* Google Analytics tracking ID has changed.
* Analytics is enabled by default.
**Fixes**: [TRNG-1260](https://jira.innoactive.de/browse/TRNG-1260)
The new tracking-ID has been tested. All analytics events were tested:
https://analytics.google.com/analytics/web/#/realtime/rt-event/a109665637w251446110p232197545
=> refactor: analytics cleanup

.azure-pipelines.yml
The development tracking ID for Google Analytics gets replaced when building a release.
=> ci: replace tracking id when releasing

Runtime/LockableObjectsCollection.cs
opening a step made a lot of missing entity exception pop up, when there was a object added to the "ToUnlock" field of a step which is not in the scene. Fixed this by cleaning up the to unlock list before using it.
=> fix: fixed a missing entity ex for missing scene objects on unlock tab

Editor/DefaultEditingStrategy.cs, Editor/GlobalEditorHandler.cs, Editor/UI/Drawers/UniqueNameReferenceDrawer.cs, Editor/UI/Windows/CourseWindow.cs, Editor/UI/Windows/StepWindow.cs
The workflow editor and the step inspector flush their content when changing scenes, additionally, if the new scene is a valid training scene with a new course, that course is loaded automatically.
Open a scene with a training course, then open a course in the workflow editor, then change the scene to:
a) a new (empty) scene.
b) another scene with a `[TRAINING_CONFIGURATION]`.
c) another scene without a `[TRAINING_CONFIGURATION]`
=> feat: displayed course changes to match scene selected TRNG-1302

Editor/UI/Wizard/Setup/TrainingSceneSetupPage.cs
wizard did not allow to continue when you wanted to create a new step by step guide while the course name was already existing.
=> fix: existing training wont stop you from starting the step guide

Editor/PackageExporter.cs
Pipeline is green while there was an error in exporting the unitypackage. This should fix it.
=> ci: exporter fails the batch command when export fails

Editor/Resources/icon_add_dark.png.meta, Editor/Resources/icon_add_light.png.meta, Editor/Resources/icon_arrow_right_dark.png.meta, Editor/Resources/icon_arrow_right_light.png.meta
My bad, old commit added meta files but kept the image type not as sprite, which makes the icons look bad.
=> chore: set new icons to editor gui type

Editor/UI/Drawers/UniqueNameReferenceDrawer.cs
**Fixes**: Previously, missing references in the step inspector were not saved, this caused an issue where scene objects were not able to be unreferenced from the step inspector. This PR fixes it by rolling back the initial change.
=> fix: issue that prevented unreferencing scene objects

Editor/UI/Graphics/Renderers/EntryNodeRenderer.cs
Add a start label below EntryNode
- [x ] Bug fix (non-breaking change which fixes an issue)
=> fix: add start button below EntryNode

Editor/UI/EditorDrawingHelper.cs, Editor/UI/Graphics/Renderers/CreateTransitionButtonRenderer.cs, Editor/UI/Graphics/Renderers/EntryJointRenderer.cs, Editor/UI/Graphics/Renderers/EntryNodeRenderer.cs, Editor/UI/Graphics/Renderers/ExitJointRenderer.cs, Editor/UI/Graphics/Renderers/StepNodeRenderer.cs, Runtime/Utils/LockObjectsOnSceneStart.cs.meta
The color of the hover effect of the transition joints spilled over to other joints.
**Before fix:**
**After fix:**
Manual UI testing.
=> fix: transition joint hover color spilled over

Editor/Configuration/DefaultEditorConfiguration.cs, Runtime/Configuration/BaseRuntimeConfiguration.cs, Runtime/Serialization/NewtonsoftJsonSerializer/ImprovedNewtonSoftJsonCourseSerializer.cs.meta, Runtime/Serialization/NewtonsoftJsonSerializer/ImprovedNewtonsoftJsonCourseSerializer.cs, Runtime/Serialization/NewtonsoftJsonSerializer/NewtonsoftJsonCourseSerializer.cs, Tests/Serialization/SerializationLengthTests.cs, Tests/Serialization/SerializationLengthTests.cs.meta
Our JSON course structure is too deep which leads to serialization errors. Easiest fix is listing the all steps in a big list at the beginning of the training JSON which removes depths. To make it backwards compatible I wrote a new serializer which is based on the old one.
Our JSON course structure is too deep which leads to serialization errors.
=> Bugfix/too long courses crash TRNG-1316

Editor/PackageManager/Dependency.cs, Editor/PackageManager/DependencyManager.cs, Editor/PackageManager/PackageOperationsManager.cs
The Dependency Manager can now install packages at specific version numbers and also import samples from the packages.
Either import the Creator to a new Unity project or go `Help > Reset Packages to defaults`, all packages should be retrieved properly.
=> The Dependency Manager now supports versioning and samples importing TRNG-1349

Editor/DefaultEditingStrategy.cs, Editor/UI/Windows/StepWindow.cs
Step Inspector will not get closed when CourseWindow closes, which applied a strange chain reaction earlier, leading to freezing unity completely.
New behavior: 
* StepInspector is not closed when CourseWindow is closed
* StepInspector target step is set to null when no CourseWindow is open and the training is changed
**Fixes**: 
* TRNG-1366
By Hand!
Nothing else required.
=> Maximizing creator tabs does not crash unity anymore

Editor/UI/Drawers/UniqueNameReferenceDrawer.cs
**Fixes**: An issue that made it possible to try to access training scene objects even when they are not present (by switching scenes), consequently a missing reference was saved.
- Open any training course
- Create a new object
- Reference that new object into any step
- Save and create a new scene (Ctrl+N)
> A missing reference error should be shown in the console, this PR fixes that.
- Open the original scene and look for the previously created object in the training
> The reference is missing, this PR fixes that.
=> The Step Inspector no longer saves references when the RuntimeConfigurator is missing TRNG-1375

Runtime/AssemblyAttributes.cs, Runtime/Properties/PropertyReflectionHelper.cs
Reworked the method a little bit to make it easier to understand, added the possibility to not include in required properties and opened the internal stuff for desktop mode which is required very soon.
=> refactor: allow to return lockables without required ones

Runtime/AssemblyAttributes.cs
Desktop Mode got moved and renamed into a proper assembly, which requires this renaming.
=> chore: renamed assembly

Editor/Unity/AssemblySymbolChecker.cs
Adds/removes BASIC_UI as define symbol automatically.
Removed it, reload Unity.
=> fix: add basic_ui to assembly symbol checker

Editor/PackageManager/Dependency.cs, Editor/PackageManager/DependencyManager.cs, Editor/PackageManager/PackageOperationsManager.cs
If provided, dependencies are now always loaded with a specific version.
**Given:** 
```csharp
public class XRInteractionPackageEnabler : Dependency
{        
/// <inheritdoc/>
public override string Package { get; } = "com.unity.xr.interaction.toolkit";
/// <inheritdoc/>
public override string Version { get; internal set; } = "1.0.0-pre.2";
/// <inheritdoc/>
public override string[] Samples { get; } = { "Default Input Actions", "XR Device Simulator" };
/// <inheritdoc/>
public override int Priority { get; } = 4;
/// <inheritdoc/>
protected override string[] Layers { get; } = {"XR Teleport"};
}
```
**When:**
- Manually switching the XRIT version on the package manager.
- Help > Reset packages to default.
- Delete the package folder at the project root.
**Then:**
XRIT must always be at …
=> Dependency Versioning TRNG-1462

Editor/Innoactive.CreatorEditor.asmdef, Editor/XRUtils/XRLoaderHelper.cs, Editor/XRUtils/XRManagementPackageEnabler.cs, Editor/XRUtils/XRProviders/XRProvider.cs
The XR Plugin Management didn't expose any API to enable XR Loaders, we came up with a solution that required reflection to enable the XR SDK that the user selected in the wizard. The newest version of the package now exposes an API to properly load the XR Loaders and the legacy private method no longer works on old Unity 1029 LTS provoking these errors:
This PR addressed both issues.
Either try a new project, import the creator, and select any xr sdk or delete the XR folder (if present) and every folder at root but Assets and then open the project again, and select any xr sdk.
The selected SDK must always be enabled after the installation and no errors should be during the process.
=> The Creator now always install requested XR SDK TRNG-1465

Editor/PackageManager/PackageOperationsManager.cs
If the XR Interaction Toolkit v1.0.0-pre.3 is installed, the Dependency Manager will downgrade to v1.0.0-pre.2, this should only happen if the installed version is lower than the target version.
Play around installing higher or lower versions of the `XR Interaction Toolkit` or the `XR Plugin Management`
=> fix: higher dependency versions are now supported TRNG-1513

Editor/UI/Drawers/StepDrawer.cs, Editor/UI/Windows/CourseWindow.cs
**Fixes**: The Step Inspector and the Workflow Editor no longer crash when Unity is building.
Build something with those windows open.
=> fix: issue where the step and workflow editor crash when building

Editor/Input/InputEditorUtils.cs
Check if folder exists because unity actually would create Resources 1-X instead of not creating an existing folder.
=> fix: keybinding creation does not duplicate folder
